<template>
    <van-sticky>
        <van-row class="backblueb" id="1">
            <van-col span="22" offset="1">
                <Goback :ModelValue="{ Title: '物料详情', Name: '测试' }"></Goback>
                <van-row class="block margin20_bottom" align="center" justify="center">
                    <van-col span="12" @click="MaterilActive = 0">
                        <van-row align="center" justify="center" :class="MaterilActive == 0 ? 'actived' : 'unactive'">
                            <van-col class="blueback"> <i
                                    class="iconfont icon-fengxiandian_jichuziliao size25"></i></van-col>
                            <van-col span="24" class="margin8_top">基础信息</van-col>
                        </van-row>
                    </van-col>
                    <van-col span="12" @click="MaterilActive = 1">
                        <van-row align="center" justify="center" :class="MaterilActive == 1 ? 'actived' : 'unactive'">
                            <van-col class="blueback"> <i
                                    class="iconfont icon-zuzhijiagou_gangweiguanshe size25"></i></van-col>
                            <van-col span="24" class="margin8_top">建筑关涉</van-col>
                        </van-row>
                    </van-col>
                </van-row>
            </van-col>
        </van-row>
    </van-sticky>
    <van-row class="height">
        <van-col span="24">
            <template v-if="MaterilActive == 0">
                <van-row class="backbluea">
                    <van-col span="22" offset="1">
                        <van-row align="center" justify="space-between">
                            <van-col span="8">
                                <van-row class="white ">
                                    <van-col span="24" class="size25 left margin10_bottom">二氯甲烷</van-col>
                                    <van-col span="24" class="font14 left margin40_bottom">CH2CI2</van-col>
                                    <van-col span="24" class="font16 left">重点监管</van-col>
                                </van-row>
                            </van-col>
                            <van-col>
                                <van-image :src="''" width="200" height="110"></van-image>
                            </van-col>
                        </van-row>
                        <van-row class="yellow margin_20_0">
                            <van-col class="font17">危险化学品、重大危险源、易制毒、易制爆</van-col>
                        </van-row>
                    </van-col>
                </van-row>
                <van-row>
                    <van-col span="22" offset="1">
                        <van-row class="borderline">
                            <van-col span="24" class="left font13 margin_7_0">英文名：Dichloromethane</van-col>
                            <van-col span="24" class="left font13 margin_7_0">物料类型：原料</van-col>
                            <van-col span="24" class="left font13 margin_7_0">物料形态：液体</van-col>
                            <van-col span="24" class="left font13 margin_7_0">物料来源：外购</van-col>
                            <van-col span="24" class="left font13 margin_7_0">储存方式：钢瓶</van-col>
                            <van-col span="24" class="left font13 margin_7_0">最大存量：50kg</van-col>
                            <van-col span="24" class="left font13 margin_7_0">年消耗量：2kg</van-col>
                            <van-col span="24" class="left font13 margin_7_0">CC、CAS码：75-09-2</van-col>
                            <van-col span="24" class="left font13 margin_7_0">化学品分类：重点监管</van-col>
                            <van-col span="24" class="left font13 margin_7_0">
                                <van-row>
                                    <van-col span="24">危险类别</van-col>
                                    <van-col>
                                        <van-row>
                                            <van-image :src="''" width="90" height="90"></van-image>
                                        </van-row>
                                    </van-col>
                                </van-row>
                            </van-col>
                        </van-row>
                        <van-row id="2" class="margin20_top borderline">
                            <van-col class="blue font18">理化数据</van-col>
                            <van-col span="24" class="left fon13 margin_7_0"
                                v-html="
                                    `外观与性状：无色透明液体，有芳香气味。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pH:熔点(C):-96.7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        相对密度（水=1）：1.33
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        沸点(C):39.8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        相对蒸气密度（空气=1）：2.93
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        分子式：CH2Cl2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        分子量：84.94
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        主要成分：
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        含量：工业级一级≥99.0%；二级≥98.0%。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        饱和蒸气压(kPa):30.5510℃)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        燃烧热(kJ/mol):604.9
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        临界温度(C):237
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        临界压力(MPa):6.08
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        辛醇/水分配系数的对数值：1.25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        闪点(C):无盗料
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        爆炸上限%V/W):19
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        引燃温度(C):615
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        爆炸下限%(VW):12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        溶解性：微溶于水，溶于乙醇、乙醚。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        主要用途：用作树脂及塑料工业的溶剂。`"></van-col>

                        </van-row>
                        <van-row id="3">
                            <van-col class="blue font18">危险特性</van-col>
                            <van-col span="24" class="left font13 margin_7_0"
                                v-html="`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                本品有麻醉作用，主要损害中枢神经和呼吸系统。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    急性中毒：轻者可有弦晕、头痛、呕吐
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    以及眼和上呼吸道粘膜刺激症状，较重者则出现易激动、步态不稳、共济失调、谐睡，可引起化学性支气管炎。重者昏迷，可有肺水肿。血中碳氧血红蛋白含量增高。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    慢性影响：
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    长期接角主要有头痛、乏力、眩晕、食欲减退、动作迟钝、嗜睡等。对皮肤有脱脂作用，
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    引起干燥、脱屑和皲裂等。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `"></van-col>
                        </van-row>
                        <van-row id="4">
                            <van-col class="blue font18">接触表现</van-col>

                        </van-row>
                        <van-row id="5">
                            <van-col class="blue font18">个人保护</van-col>

                        </van-row>
                        <van-row id="6">
                            <van-col class="blue font18">灭火方法</van-col>

                        </van-row>
                        <van-row id="7">
                            <van-col class="blue font18">泄露处理</van-col>

                        </van-row>
                        <van-row id="8">
                            <van-col class="blue font18">急救措施</van-col>

                        </van-row>
                        <van-row id="9">
                            <van-col class="blue font18">毒理学</van-col>

                        </van-row>
                        <van-row id="10">
                            <van-col class="blue font18">用途</van-col>

                        </van-row>
                        <van-row id="11">
                            <van-col class="blue font18">救援</van-col>

                        </van-row>
                    </van-col>
                </van-row>
                <van-row>
                    <van-col span="24">

                        <van-back-top class="custom ">返回顶部</van-back-top>
                    </van-col>
                </van-row>
                <div class="flexd card whiteback border ">
                    <template v-for="(v, k) in AnchorList" :key="k">
                        <div class="padding_10_0" @click="jumpAnchor(k + 1)">{{ v }}</div>
                    </template>
                </div>
            </template>
            <template v-if="MaterilActive == 1">
                <van-row>
                    <van-col span="22" offset="1">
                        <van-row class=" margin1915">
                            <van-col class="font15"> 建构筑物</van-col>
                        </van-row>
                        <van-row class="card whiteback">
                            <van-col span="22" offset="1">
                                <van-row align="center" justify="space-between" class="block">
                                    <van-col><van-image :src="''" width="40" height="40"></van-image></van-col>
                                    <van-col span="20">
                                        <van-row class="block">
                                            <van-col span="24">
                                                <van-row align="center" justify="space-between">
                                                    <van-col>1.生产车间建筑主体</van-col>
                                                    <van-col> 钢混结构</van-col>
                                                </van-row>
                                            </van-col>
                                            <van-col class="grey">耐火等级：一级 &nbsp;火灾危险性：甲</van-col>
                                            <van-col class="grey">层数：26 &nbsp;总高度：38m &nbsp;占地面积：2654㎡</van-col>
                                        </van-row>
                                    </van-col>
                                </van-row>
                            </van-col>
                        </van-row>
                    </van-col>
                </van-row>
                <van-row class="line_gray"></van-row>
                <van-row>
                    <van-col span="22" offset="1">
                        <van-row class="margin1915">
                            <van-col class="font15">工艺流程</van-col>
                        </van-row>
                        <van-row class="card whiteback">
                            <van-col span="22" offset="1">
                                <van-row align="center" justify="space-between" class="block">
                                    <van-col><van-image :src="''" width="40" height="40"></van-image></van-col>
                                    <van-col span="20">
                                        <van-row class="block">
                                            <van-col span="24">
                                                <van-row align="center" justify="space-between">
                                                    <van-col>1.硝化工艺流程</van-col>
                                                    <van-col> 危险工艺</van-col>
                                                </van-row>
                                            </van-col>
                                            <van-col class="grey">耐火等级：一级 &nbsp;火灾危险性：甲</van-col>
                                            <van-col class="grey">层数：26 &nbsp;总高度：38m &nbsp;占地面积：2654㎡</van-col>
                                        </van-row>
                                    </van-col>
                                </van-row>
                            </van-col>
                        </van-row>
                    </van-col>
                </van-row>
                <van-row class="line_gray"></van-row>
                <van-row>
                    <van-col span="22" offset="1">
                        <van-row class="margin1915">
                            <van-col class="font15">关涉岗位</van-col>
                        </van-row>
                        <van-row class="card whiteback">
                            <van-col span="22" offset="1">
                                <van-row align="center" justify="space-between" class="block">
                                    <van-col><van-row align="center" justify="center">
                                            <i class="iconfont icon-zuzhijiagou_gangwei-biaotou"></i> <span
                                                class="font15">总调度长</span>
                                        </van-row></van-col>
                                    <van-col class="blue">
                                        <i class="iconfont icon-zuzhijiagou_renyuan-xianxing font12"></i><span
                                            class="font14">01</span>&nbsp;<i
                                            class="iconfont icon-anquanpeixuntubiao_jinru1 font12"></i>
                                    </van-col>
                                </van-row>
                            </van-col>
                        </van-row>
                    </van-col>
                </van-row>
                <van-row class="line_gray"></van-row>

            </template>
        </van-col>
    </van-row>
</template>
<script setup lang='ts'>
import { computed, defineComponent, ref, reactive, onMounted, watch } from 'vue';
import { SearchResult } from '@ctsy/api-sdk';
import { SearchWhere } from '@ctsy/api-sdk/dist/lib';
import Goback from '../component/goback.vue';

const MaterilActive = ref(0)


const Height = computed(() => {
    let top = document.querySelector('.backblueb')
    return window.innerHeight - top?.clientHeight + 'px'
})
const AnchorList = ref("基础信息，理化特性，危险特性，接触表现，个体保护，灭火方法，泄露处置，急救措施，毒理学，用途，救援".split('，'))
const jumpAnchor = (n: number) => {
    let anchor = document.getElementById(`${n}`)
    document.documentElement.scrollTop = anchor.offsetTop;
}
</script>
<style scoped lang='less'>
.blueback {
    width: 37px;
    height: 37px;
    line-height: 37px;
    background: #64a4fe;
    border-radius: 4px;
}

.height {
    min-height: v-bind(Height);
    background: #f7f9fc;
}

.backbluea {
    background-color: #1b6ffe;
}

.flexd {
    position: fixed;
    right: 10px;
    bottom: 50px;
}

.border {
    background: rgba(255, 255, 255, 0.8);
    border: 2px solid;
    border-color: #e6e6e6;
    box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.1);
    border-radius: 16px
}

.custom {
    width: 100%;
    text-align: center;
}
</style>